# Generated by Django 5.2.6 on 2025-10-06 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaXLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('cufe', models.CharField(max_length=255, unique=True)),
                ('folio', models.CharField(blank=True, max_length=100, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=50, null=True)),
                ('nit_emisor', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_emisor', models.CharField(blank=True, max_length=255, null=True)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaXML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesador.proveedor')),
            ],
        ),
    ]
