# Generated by Django 5.2.6 on 2025-10-16 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesador', '0002_tarifaica_retencion'),
        ('procesador', '0003_facturaxls_fecha_documento'),
    ]

    operations = [
    ]
