# Generated by Django 5.2.6 on 2025-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesador', '0006_cuentacontableproveedor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retencion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='cuenta_contable',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='TarifaICA',
        ),
        migrations.DeleteModel(
            name='Retencion',
        ),
    ]
